apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080        # port truy cập từ cluster/host
      targetPort: 80    # port container
      nodePort: 30080   # port NodePort
