name: CI (Build, Push & Update manifest)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${IMAGE_TAG}

      - name: Update image tag in deploy repo
        run: |
          IMAGE_TAG=${{ github.sha }}
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/minhduc3105/k8s-config.git
          cd deploy-repo/manifests
          sed -i "s#image: .*#image: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${IMAGE_TAG}#" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag to ${IMAGE_TAG}"
          git push
